### ISSUE TITLE
Multisig support

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-blockstack#54]

**Comment by kantai** [comment]
As part of multisig support, it would be very useful to allow the `5757'` derivation path prefix in addition to the current `44'/5757'` prefix. The `5757'` prefix was used in multisig wallet setups in Stacks 1.0, where the derivation path was similar to the derivation path used for bitpay multisig and electrum multisig:

```
m/5757'/<account-index>'/<co-signer-index>/<change>/<address-index>
```

Where instead of the `45'` purpose, `5757'` is used.


e.g.,
```
m/5757'/0'/0/0/0
m/5757'/0'/0/0/1
...
```

**Comment by kyranjamie** [comment]
@kantai unless there's some issue where it rejects that path (I haven't checked), the client lib lets you to define the derivation path at runtime.

Such as:
https://github.com/Zondax/ledger-blockstack/blob/91a5a75181316182d4ba79fc7a2ad9dc410908d1/js/src/index.ts#L149

So no additional changes should be needed (other than https://github.com/Zondax/ledger-blockstack/issues/52)
